### ISSUE TITLE
Unable to extract from Sphinx (PS2)

### ISSUE THREAD

**Issue by joshbarrass** [eurotools/eurochef#31]
Maybe I'm just doing something wrong, but I can't seem to extract anything from Sphinx and the Cursed Mummy (PS2), despite the readme claiming it should work. I've tried the latest release, e5cbb1a and `main` (a5cbbd6b76b62a8a71dd0f088ea151e8ac42e375 at the time of writing), but nothing seems to be able to extract anything. For reference, I have predominantly been testing using the `*_sphin.edb` files (e.g. `cs_sphin.edb`, `mc_sphin.edb`, etc.).

The CLI on `main` seems to be the only version to extract any sort of texture, but has thus far only produced corrupted textures and repeatedly gives the error `eurochef_cli::edb::textures: Failed to read frame 0`. Attempting to open the file with the GUI causes a panic with the message `Vertex format for version 182 is not known yet, report to cohae!`

Every other version I've tried seems to either ignore the contents of the files, or the GUI will also just immediately crash whenever I try to open something.

Am I just using the program wrong, or has there been some sort of recent regression? As far as I can tell from the readme, support for Sphinx/EDB 182 should be golden, as should extracting PS2 textures, but I can't seem to get anything to work.

**Comment by Swyter** [comment]
Hi, Josh. Sphinx support probably isn't the best right now in cohae's codebase, because there is less of a need for extracting and unpacking Sphinx assets; we released the [Authoring Tools DLC](https://store.steampowered.com/app/750430/Sphinx_and_the_Cursed_Mummy_Authoring_Tools/) officially with the PC version, and that lets you essentially open, extract and edit every single file you mention with Euroland, and more.

Even outputting back EDB files that can be played on PS2, GameCube and Xbox. If any of that sounds interesting, join us at *https://discord.gg/sphinx* or post in the Steam Community forums and we'll help you out. ¯\\\_(ツ)_/¯

**Comment by cohaereo** [comment]
The readme is kind of confusing, a game is marked as "supported" if it works on any platform. Any further platform specifics such as textures, sound and mesh are denoted in the platforms matrix, though this doesnt always guarantee it will work.

Sphinx is pretty much out of scope because of the existing authoring tools, and Eurochef lacks decent support for PS2 textures and models.

**Comment by joshbarrass** [comment]
Thanks for the speedy replies!

Regarding @Swyter's comments: my issue is unfortunately somewhat loaded! :sweat_smile: My interest here was actually in targeting _Buffy The Vampire Slayer: Chaos Bleeds_, which uses EDB files with version 170, rather than actually targeting Sphinx. I know Chaos Bleeds and Sphinx are very similar (I believe in some cases they use the same code for things), and I have some older QuickBMS scripts designed to extract assets from Sphinx and Hero's Tail that also work on Chaos Bleeds. However, these are only able to extract the meshes -- no textures or UVs -- so I have to dump the textures via PCSX2 and manually recreate the UV map. I was hoping that, since the readme claims support with Sphinx and Hero's Tail, I might be able to get a little further using eurochef (and maybe make some contributions if possible), but wanted to try it with a supported game first, rather than jumping straight to an unlisted game. That said, it would seem (based on the support matrix at least) that Xbox support is better than other platforms, so I can always try working with the Xbox version of Chaos Bleeds instead and see if that goes any better.

Regarding @cohaereo's comments: ah I see. Yeah the readme is a little confusing in that case. A shame about the PS2 support, though from my understanding of it the PS2 itself complicated things a lot. 

Since this issue was really a stopgap towards working on a different, not-officially-supported game, more than an actual issue, I'm happy for it to be closed if you guys want.
